# NUMPY & INBUILT FUNCTION

# Numpy

Numpy is a general-purpose array processing package. It provides high multidimensional array object, and tools for working with these arrays.It is the fundamental package for scientific computing with python.

# Array

An array is a data-structure that stores values of same data type.In python,this is the main difference between  arrays and lists.While python lists can contain values corresponding to different data types,arrays in python can only contain values corresponding to same data type.

In [5]:
pip install numpy


The following command must be run outside of the IPython shell:

    $ pip install numpy

The Python package manager (pip) can only be used from outside of IPython.
Please reissue the `pip` command in a separate terminal or command prompt.

See the Python documentation for more information on how to install packages:

    https://docs.python.org/3/installing/


In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5]

In [3]:
arr=np.array(my_lst)

In [4]:
type(arr)

numpy.ndarray

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
arr.shape

(5,)

In [8]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr.reshape()

In [10]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [11]:
arr.shape

(3, 5)

In [12]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [14]:
arr.shape

(3, 5)

In [16]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

# Indexing

In [19]:
arr =np.array([1,2,3,4,5,6,7,8,9])

In [20]:
arr[3]

4